// CSV export for draft rankings. Pure functions + a browser download helper.
//
// The shape below is structurally satisfied by the DraftRanking interface in
// DraftRankingsView, so callers can pass their rankings array directly without
// the type being exported from the component.

export interface ExportableRanking {
  overallRank: number;
  positionRank: number;
  tier: number;
  projectedPoints: number | null;
  adp: number | null;
  adpDelta: number | null;
  rationale: string;
  player: {
    name: string;
    position: string;
    team: string;
    age: number | null;
  };
}

function quoteIfNeeded(s: string): string {
  return /[",\n\r]/.test(s) ? `"${s.replace(/"/g, '""')}"` : s;
}

// Free-text cells can come from player names or LLM-generated rationale. A
// leading =, +, -, @, tab or CR lets a spreadsheet interpret the value as a
// formula (CSV injection), so neutralize it with a leading apostrophe. Numeric
// cells are generated by us and emitted raw (so negative deltas stay readable).
function textCell(value: string): string {
  const guarded = /^[=+\-@\t\r]/.test(value) ? `'${value}` : value;
  return quoteIfNeeded(guarded);
}

function numCell(value: number | null, digits?: number): string {
  if (value == null) return '';
  return digits != null ? value.toFixed(digits) : String(value);
}

const HEADER = ['Rank', 'Player', 'Position', 'Team', 'Age', 'Proj Pts', 'ADP', 'Value Delta', 'Tier', 'Rationale'];

export function rankingsToCsv(rankings: ExportableRanking[]): string {
  const lines = [HEADER.join(',')];
  for (const r of rankings) {
    lines.push(
      [
        numCell(r.overallRank),
        textCell(r.player.name),
        textCell(`${r.player.position}${r.positionRank}`),
        textCell(r.player.team),
        numCell(r.player.age),
        numCell(r.projectedPoints, 1),
        numCell(r.adp, 1),
        numCell(r.adpDelta, 1),
        numCell(r.tier),
        textCell(r.rationale),
      ].join(','),
    );
  }
  return lines.join('\r\n');
}

export function downloadRankingsCsv(rankings: ExportableRanking[], filename: string): void {
  const csv = rankingsToCsv(rankings);
  const blob = new Blob([csv], { type: 'text/csv;charset=utf-8;' });
  const url = URL.createObjectURL(blob);
  const a = document.createElement('a');
  a.href = url;
  a.download = filename;
  document.body.appendChild(a);
  a.click();
  document.body.removeChild(a);
  URL.revokeObjectURL(url);
}
